---

- name: Install packages.
  apt: pkg=libapache2-mod-proxy-html state=present

- name: Enable modules
  command: a2enmod {{ item }} creates={{ apache_conf_path }}/mods-enabled/{{ item }}.load
  notify: restart apache
  with_items:
    - proxy_http
    - proxy_html
    - xml2enc

- name: Creating maildev htpasswd entries
  copy:
    content: |
      {% for line in apache_maildev_htpasswd_file %}
      {{ line }}
      {% endfor %}
    dest: "{{ apache_conf_path }}/htpasswd/maildev"
    owner: root
    group: www-data
    mode: 0640
  notify: restart apache

- name: Add mailcatcher site configuration file.
  template: >
    src=site-proxy-maildev.j2 dest={{ apache_conf_path }}/sites-available/maildev{{ apache_site_file_suffix }} mode=644
  notify: restart apache

- name: Enable the maildev site.
  command: >
    a2ensite maildev creates=/etc/apache2/sites-enabled/maildev{{ apache_site_file_suffix }}
  notify: restart apache
  when: apache_maildev_enable_site
  notify: restart apache

- name: Disable the maildev site.
  command: >
    a2ensite maildev creates=/etc/apache2/sites-enabled/maildev{{ apache_site_file_suffix }}
  notify: restart apache
  when: not apache_maildev_enable_site
  notify: restart apache

